spring:
  #???
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&characterEncoding=utf8
  #???
  devtools:
    restart:
      exclude: static/**,public/**,/config/application.yml
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #??????
    map-underscore-to-camel-case: false
server:
  port: 80
